server:
  port: 80

feign:
  hystrix:
    enabled: true

eureka:
  client:
    # 代表不向注册中心注册自己
    register-with-eureka: false    # UNKNOWN	n/a (1)	(1)	UP (1) - USER-20171223ZD:80
    # 是否需要去注册中心检索服务
#    fetch-registry: false # No instances available for microservicecloud-dept
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/