server:
  port: 7001

eureka:
  instance:
    hostname: localhost  #eureka服务端实例名称
  client:
    # 代表不向注册中心注册自己（集群的时候需要设为true）
    register-with-eureka: false
    # 是否需要去注册中心检索服务（集群的时候需要设为true）
    fetch-registry: false
    # 设置与Eureka Server交互的地址查询服务和注册服务
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/