server:
  port: 80

eureka:
  client:
    # 代表不向注册中心注册自己（集群的时候需要设为true）
    register-with-eureka: false
    # 是否需要去注册中心检索服务（集群的时候需要设为true）
    fetch-registry: false
#    service-url:
#          defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7003.com:7003/eureka/,http://eureka7002.com:7002/eureka/