server:
  port: 8001

mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml
  type-aliases-package: com.qhjys.springcloud.entities
  mapper-locations: classpath:com/qhjys/springcloud/mapper/*.xml

spring:
  application:
    name: microservicecloud-dept
  datasource:
    url: jdbc:mysql://localhost:3306/test-cloud?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC&useLegacyDatetimeCode=false
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
#  redis:
#    host: localhost
#    password:
#    port: 6379
#    timeout: 5000ms
#    database: 4

eureka:
  client:
    # 代表不向注册中心注册自己（集群的时候需要设为true）
    register-with-eureka: false
    # 是否需要去注册中心检索服务（集群的时候需要设为true）
    fetch-registry: false